import type { Rarity } from "./types";

export const itemAdjectives: Record<Rarity, string[]> = {
  common: [
    "Rusted",
    "Weathered",
    "Rugged",
    "Timeworn",
    "Tarnished",
    "Plain",
    "Chipped",
    "Battered",
  ],
  uncommon: [
    "Gleaming",
    "Sturdy",
    "Pristine",
    "Serrated",
    "Reinforced",
    "Piercing",
    "Tranquil",
    "Balanced",
  ],
  rare: [
    "Enchanted",
    "Runic",
    "Venomous",
    "Savage",
    "Resilient",
    "Ornate",
    "Molten",
    "Frozen",
    "Feral",
  ],
  epic: [
    "Formidable",
    "Ancient",
    "Cursed",
    "Blessed",
    "Radiant",
    "Ethereal",
    "Vengeful",
    "Shadowed",
    "Arcane",
    "Spectral",
  ],
  legendary: [
    "Celestial",
    "Infernal",
    "Hallowed",
    "Gilded",
    "Doomed",
    "Sundered",
    "Glorious",
    "Malevolent",
    "Unyielding",
    "Shattered",
  ],
};
